name = "nad-finance"
compatibility_date = "2025-01-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://zvehsmptbxlgeuahhoqu.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZWhzbXB0YnhsZ2V1YWhob3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc5MzUyOTYsImV4cCI6MjA0MzUxMTI5Nn0.SMJrfcP0IT4bq8zC9o5ojEuqf7yEoFEpb6jronYfqr4"
NEXT_PUBLIC_SUPABASE_EMAIL = "liny52@163.com"
NEXT_PUBLIC_SUPABASE_EMAIL_PASSWORD = "w@C@64dJeciDWqT"